### PR TITLE
Added code to donate route / component

### PR DESCRIPTION
**Pull request by benjahmin-koenigsberg**
I wrote a little jsx for the donate route. Did my best to match the mock up XD page that are linked in the readme.

 I was not getting errors locally but was when added code to qc-frontend-v2 repo, so I changed the file extension to .js. I added a css file for the styling. 

I am requesting a pull to the mb-donate branch from a personal branch I created after forking and cloning the repo

donate code

### CODE REVIEW

**Comment by Githubbubber** [comment]
It looks like there is an accidental push of all files. Are you able to undo the commit and re-stage what file(s) you changed @benjahmin-koenigsberg?

**Comment by benjahmin-koenigsberg** [comment]
will attempt to make a pr only for the two files i worked on

**Comment by Githubbubber** [comment]
> will attempt to make a pr only for the two files i worked on

I have time if you need any help. It’s fun. Just hit me up on Slack.

**Comment by benjahmin-koenigsberg** [comment]
Hi, that would be great!
Thank you. I am new to git flow

I am not on the slack channel yet. do you have good email or Linkedin to
reach you

I can research more about just committing these two files to  a new branch
and then making a pr from that branch...?

**Comment by Githubbubber** [comment]
Sounds good. Let's let you research it and revisit the changes.

**Pull request closed without merging**
